/* Copyright (c) 2022-2024 4Players GmbH. All rights reserved. */

#pragma once

#include "odin_sdk.h"

#include "DSP/Dsp.h"
#include "Sound/SoundGenerator.h"

class FOdinPlaybackStreamReader;
class IAudioBufferListener;

class ODIN_API OdinMediaSoundGenerator : public ISoundGenerator
{
  public:
    /**
     * Set the OdinMediaStream to be used by the OdinMediaSoundGenerator for reading voice data.
     *
     * @param NewStreamHandle - The handle to the OdinMediaStream to set. Must not be 0.
     */
    [[deprecated("Please use SetStreamReader to provide an Odin Playback Stream Reader.")]]
    void SetOdinStream(OdinMediaStreamHandle NewStreamHandle);

    /**
     * Sets the stream reader for retrieving the playback stream audio.
     * @param StreamReader Pointer to Odin Playback Stream Reader for retrieving playback stream
     * audio.
     */
    void
    SetStreamReader(const TSharedPtr<FOdinPlaybackStreamReader, ESPMode::ThreadSafe>& StreamReader);

    // Called by the sound system when a new buffer is required.
    virtual int32 OnGenerateAudio(float* OutAudio, int32 NumSamples) override final;

    // Returns the number of samples to render per callback.
    virtual int32 GetDesiredNumSamplesToRenderPerCallback() const override
    {
        return 1920; // 20ms 48kHz stereo
    }

    /**
     * Add a listener to the Audio generated by the OdinMediaSoundGenerator.
     *
     * @param InAudioBufferListener - Pointer to an object implementing the IAudioBufferListener
     * interface.
     */
    void AddAudioBufferListener(IAudioBufferListener* InAudioBufferListener);
    /**
     * @param InAudioBufferListener The audio buffer listener to remove.
     */
    void RemoveAudioBufferListener(IAudioBufferListener* InAudioBufferListener);

  private:
    TSharedPtr<FOdinPlaybackStreamReader, ESPMode::ThreadSafe> PlaybackStreamReader;

    /**
     * Used to keep track of our read progress on the circular buffer of the playback media. This
     * way multiple sound generators can playback audio from the same odin media stream without
     * leading to an audio buffer underrun.
     */
    int32 PlaybackStreamReadIndex = 0;
};