/* Copyright (c) 2022-2023 4Players GmbH. All rights reserved. */

#pragma once

#include "DSP/Dsp.h"
#include "OdinNative/OdinNativeHandle.h"
#include "HAL/ThreadSafeBool.h"
#include "Sound/SoundGenerator.h"

class IAudioBufferListener;
class UOdinDecoder;

/**
 * FOdinSoundGenerator
 *
 * An implementation of ISoundGenerator that pulls audio data from an Odin decoder
 * and provides it to the Unreal Audio Engine.
 */
class ODIN_API FOdinSoundGenerator : public ISoundGenerator
{
  public:
    FOdinSoundGenerator();
    ~FOdinSoundGenerator();
    void ResetConnectedDecoder();

    /**
     * Sets the Odin decoder instance used to fetch audio data.
     * @param InDecoder The UOdinDecoder to pull audio from.
     */
    void SetOdinDecoder(UOdinDecoder* InDecoder);

    /**
     * Closes the generator and stops audio processing.
     */
    void Close();

    /**
     * Adds a listener that will receive the raw audio buffers generated by this instance.
     * @param InAudioBufferListener A weak pointer to the listener interface.
     */
    void AddAudioBufferListener(const TWeakPtr<IAudioBufferListener>& InAudioBufferListener);

    /**
     * Removes a previously added audio buffer listener.
     * @param InAudioBufferListener A weak pointer to the listener to remove.
     */
    void RemoveAudioBufferListener(const TWeakPtr<IAudioBufferListener>& InAudioBufferListener);

    /**
     * Returns the number of samples the generator prefers to render per callback.
     * @return The preferred number of samples.
     */
    virtual int32 GetDesiredNumSamplesToRenderPerCallback() const override;

    /**
     * Called on audio generator thread right when the generator begins generating.
     */
    virtual void OnBeginGenerate() override;

    /**
     * Called when a new buffer is required by the audio engine.
     * @param OutAudio The buffer to fill with audio data.
     * @param NumSamples The number of samples requested.
     * @return The number of samples actually generated.
     */
    virtual int32 OnGenerateAudio(float* OutAudio, int32 NumSamples) override;

    /**
     * Called on audio generator thread right when the generator ends generating.
     */
    virtual void OnEndGenerate() override;

    /**
     * Checks if the sound generator has finished its playback.
     * @return True if finished, false otherwise.
     */
    virtual bool IsFinished() const override;

  private:
    TWeakObjectPtr<UOdinHandle>            OdinDecoderHandle;
    TArray<TWeakPtr<IAudioBufferListener>> AudioBufferListeners;
    FCriticalSection                       CriticalSectionAudioBufferListeners;

    OdinDecoder*     NativeDecoderHandle;
    FCriticalSection NativeHandleAccessSection;

    FThreadSafeBool bIsFinished;

    int32 SampleRate   = 48000;
    int32 ChannelCount = 1;
};